function params = createUE(params)
    load(params.infra.UE.configFile,"uelat","uelon");
    userindex = sort(randperm(params.infra.UE.candidateNumber, params.infra.UE.number));
    params.infra.UE.originalIndex = userindex;
    params.infra.UE.latitude = uelat(userindex);
    params.infra.UE.longitude = uelon(userindex);
    params.infra.UE.rxsite = rxsite("Name",params.infra.UE.name,...
                "Latitude",params.infra.UE.latitude,...
                "Longitude",params.infra.UE.longitude,...
                "Antenna",params.infra.UE.antenna,...
                "AntennaHeight",params.infra.UE.antennaHeight,...
                "ReceiverSensitivity",params.infra.RS.receiverSensitivitydB);
end